### ISSUE TITLE
git clone的地址不能访问

### ISSUE THREAD

**Issue by willwong123** [17/hexo-theme-strict#10]
- readme中git@的方式换成https的便可以访问了
- 克隆下来的文件夹名称是`hexo-theme-strict`，而说明文档中提到修改_config.yml的theme为strict，应该为**hexo-theme-strict**

**Comment by 17** [comment]
```
$ git clone git@github.com:unmric/hexo-theme-strict.git themes/strict
```

`git@` 使用的是 ssh 你检查下 Github 的密钥是否正常? 
至于克隆的目录的名称, 应该是更换的时候不小心把后面 `themes/strict` 参数删除掉了. 
gl ; )

**Comment by willwong123** [comment]
@unmric 还有个问题想请教一下

在你的demo里面，日本语那一块的**READ MORE**是配置了哪里生成的呢？

**Comment by 17** [comment]
写文章的时候可以用 `<!-- more -->` 标签分割文章, 这样前一部分就会显示在首页, 其余的点开文章就会显示出来. (应该没错, 如果 hexo 没有改的话.)

**Comment by willwong123** [comment]
@unmric 试过，可以用，thx
