### ISSUE TITLE
换了Mac之后新装hexo，使用strict报错了

### ISSUE THREAD

**Issue by akring** [17/hexo-theme-strict#11]
所有数据迁移到新Mac上之后，使用hexo -g，hexo -s命令均无报错，在本地环境中打开blog之后页面输出了一段提示代码如下：

include _views/post include _views/menu extends _views/main block main -page.posts.each(function(post){ +post(post, 'index') -}) block head title = config.title block menu +menu('index')

换用其他主题，如默认的和Pacman等均正常，因为小白一个，对前端实在是不了解，求教下这个提示是什么地方不对呢？

环境：
hexo: 3.1.1
os: Darwin 14.4.0 darwin x64
http_parser: 2.3
node: 0.12.5
v8: 3.28.71.19
uv: 1.6.1
zlib: 1.2.8
modules: 14
openssl: 1.0.1o

已安装hexo-renderer-jade

**Comment by 17** [comment]
`hexo-renderer-jade` 没装对地方, 应该是 hexo 生成的目录.
你再安装试试.

**Comment by akring** [comment]
OK了，问题已解决，之前安装的时候没有加上 --save，重新安装后就好啦，为你这么晚还来处理issue点赞👍
