### ISSUE TITLE
MathJax对齐问题

### ISSUE THREAD

**Issue by fuyuhin** [17/hexo-theme-strict#13]
下面是写在Markdown中的源码，在Atom等编辑器上没有问题，post之后页面就有问题了
1. 不能对齐
2. 公式内不能换行

``` Latex
$$
    \begin{align}
    \Delta y = & f(x_0+\Delta x) - f(x_0) \\
    = & (x_0+\Delta)^3 - x_0^3 \\
    = & 3x_0^2 \Delta x + 3 x_0 (\Delta x)^2 + (\Delta x)^3 \\
    \end{align}
$$
$$
\begin{equation}
\begin{split}
a& =b+c-d\\
& \quad +e-f\\
& =g+h\\
& =i
\end{split}
\end{equation}
$$
```

**Comment by 17** [comment]
你用什么插件显示公式的, 我检查一下是那部分的 CSS 样式影响了公式的对齐.

**Comment by 17** [comment]
我依照 "[Hexo MathJax 插件](http://catx.me/2014/03/09/hexo-mathjax-plugin/)" debug 了一下, 没有发现有问题.
插件使用的是 span 标签, 并且有着很严格的 CSS 重置. 方便的话你可以贴一下 demo 我再细查一下.

**Comment by fuyuhin** [comment]
我用的也是这个插件，我查出原因了。换行不能用 `\\` ，用  `\newline` 就好了。
demo: fuyuhin.github.com

**Comment by 17** [comment]
对齐指的是?

**Comment by fuyuhin** [comment]
对齐指若干行公式等号对齐。对不齐是由于换行引起的，换行解决了，对齐自然就好了

**Comment by fuyuhin** [comment]
还是有莫名奇妙的问题，求帮忙...
demo: http://fuyuhin.github.io
用Hexo处理Markdown后，Latex就各种不识别。都是坑啊！
第一篇文章源代码：
```Latex
$$
I(a_0,a_1,\cdots,a_n)=\sum_{i=0}^m (S(x_i)-y_i)^2 \newline
S(x)=a_0\varphi_0(x) + a_1\varphi_1(x) + \cdots + a_n\varphi_n(x) \newline
\frac{\partial I}{\partial a_k} = 2 \sum_{i=0}^m [S(x_i)-y_i] \varphi_k(x_i)  = 0 \newline
$$
```

**Comment by 17** [comment]
这个是 Markdown 解析的问题, MathJax 中的下划线和 Markdown 中的斜体的标签重叠了, 这时应该用 `\` 反注释 MathJax 中的下划线. 

http://catx.me/2014/03/09/hexo-mathjax-plugin/ 下面评论有相关评论.
