### ISSUE TITLE
关于Jade模板的使用问题

### ISSUE THREAD

**Issue by ghost** [17/hexo-theme-strict#14]
想问一下你是怎样遍历posts的？看到官网上说要用site.posts.toArray()，但是我在运行的时候连site都找不到，因此无法遍历，但是Jade模板引擎可以用。请问需要修改什么配置吗？

**Comment by 17** [comment]
`page.posts` 的遍历在这个文件([layout/index.jade#L6](https://github.com/17/hexo-theme-strict/blob/master/layout/index.jade#L6))
使用 Jade 需要安装 `hexo-renderer-jade`, 除此之外应该没有别的了.

**Comment by ghost** [comment]
请问按照`nam install hero-renderer-jade --save-dev`命令安装之后，还需要什么配置吗？Jade引擎可以渲染出网页的静态部分，但是site, page等变量还是找不到。

**Comment by 17** [comment]
不需要, 如果找不到变量, 先确定文件名和文件夹是否符合主题的格式, 再用 `console.log` 检查一下吧.

**Comment by ghost** [comment]
解决了，原来是因为使用了layout.jade之后再使用index.jade，则不能用block扩展，而是像ejs一样直接放内容。谢谢~
