### ISSUE TITLE
Another weird problem about the copy character '&copy;' at footer.

### ISSUE THREAD

**Issue by 2hu12** [17/hexo-theme-strict#5]
At the beginning, it's ok. But after several blogs generated, I found that the © was displayed as raw text.
![image](https://cloud.githubusercontent.com/assets/5362563/3160792/14064816-eb25-11e3-8716-dbc69835a11c.png)
And I find the index.html in '/pulbic' was generated as `&amp;copy;`.

When I changed back to the dafault landscape theme, it solved. But when I change to strict again, the problem still exist.

**Comment by 17** [comment]
done, thank you!
