### ISSUE TITLE
国内Google服务被墙导致的加载缓慢

### ISSUE THREAD

**Issue by akring** [17/hexo-theme-strict#7]
href='//fonts.googleapis.com/css?family=Source+Code+Pro')

由于被墙，导致以上连接无法访问，进而导致了每次加载页面的时候都会卡到超时，挂上VPN即可解决这个问题，望作者能针对国内网络环境做一些更新

**Comment by 17** [comment]
这个字体并不影响主体效果, 只是代码显示的时候需要, 如果觉得慢可以去掉.
国内似乎没有支持 HTPPS 的谷歌字体 CDN, 有什么好的推荐吗?

**Comment by akring** [comment]
如果对360不反感的话，我找到了这个
360网站卫士提供的公共库资源( http://libs.useso.com/ )

**Comment by akring** [comment]
顺便想请问下如何集成多说评论框，我是前端小白。。。多多包涵
BTW:还想请问下是否支持fancybox呢？感谢

**Comment by 17** [comment]
明天休息, 我再把排版重构下, 顺便留给个接口方便使用多说的同学.
360 不支持 HTPPS. 谷歌字体我想想办法或者把它去掉.

**Comment by akring** [comment]
好的，多谢了
